/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mhe_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[45] = {41, 1, 0, 41, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40};
static const casadi_int casadi_s3[85] = {32, 41, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 16, 17, 18, 26, 27, 28, 29, 30, 31, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const casadi_int casadi_s4[3] = {41, 0, 0};

/* mhe_cost_y_0_fun_jac_ut_xt:(i0[16],i1[16],i2[],i3[])->(o0[41],o1[32x41,41nz],o2[41x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+3, *w2=w+6, *w3=w+9, *w4=w+12, *w5=w+16, *w6=w+57, *w7=w+89, *w8=w+92, *w9=w+96, *w10=w+99, *w11=w+102, *w12=w+105;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w1);
  /* #3: output[0][1] = @1 */
  if (res[0]) casadi_copy(w1, 3, res[0]+3);
  /* #4: @2 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+13 : 0, 3, w2);
  /* #5: output[0][2] = @2 */
  if (res[0]) casadi_copy(w2, 3, res[0]+6);
  /* #6: @3 = input[1][0] */
  casadi_copy(arg[1], 3, w3);
  /* #7: output[0][3] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+9);
  /* #8: @4 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 4, w4);
  /* #9: output[0][4] = @4 */
  if (res[0]) casadi_copy(w4, 4, res[0]+12);
  /* #10: @3 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+7 : 0, 3, w3);
  /* #11: output[0][5] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+16);
  /* #12: @3 = input[1][3] */
  casadi_copy(arg[1] ? arg[1]+10 : 0, 3, w3);
  /* #13: output[0][6] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+19);
  /* #14: @3 = input[1][4] */
  casadi_copy(arg[1] ? arg[1]+13 : 0, 3, w3);
  /* #15: output[0][7] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+22);
  /* #16: output[0][8] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+25);
  /* #17: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w4);
  /* #18: output[0][9] = @4 */
  if (res[0]) casadi_copy(w4, 4, res[0]+28);
  /* #19: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w0);
  /* #20: output[0][10] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+32);
  /* #21: output[0][11] = @1 */
  if (res[0]) casadi_copy(w1, 3, res[0]+35);
  /* #22: output[0][12] = @2 */
  if (res[0]) casadi_copy(w2, 3, res[0]+38);
  /* #23: @5 = zeros(32x41,41nz) */
  casadi_clear(w5, 41);
  /* #24: @6 = ones(32x1) */
  casadi_fill(w6, 32, 1.);
  /* #25: {@2, @4, @1, @0, @3, @7, @8, @9, @10, @11} = vertsplit(@6) */
  casadi_copy(w6, 3, w2);
  casadi_copy(w6+3, 4, w4);
  casadi_copy(w6+7, 3, w1);
  casadi_copy(w6+10, 3, w0);
  casadi_copy(w6+13, 3, w3);
  casadi_copy(w6+16, 3, w7);
  casadi_copy(w6+19, 4, w8);
  casadi_copy(w6+23, 3, w9);
  casadi_copy(w6+26, 3, w10);
  casadi_copy(w6+29, 3, w11);
  /* #26: @12 = vertcat(@7, @10, @11, @2, @4, @1, @0, @3, @7, @8, @9, @10, @11) */
  rr=w12;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  /* #27: (@5[:41] = @12) */
  for (rr=w5+0, ss=w12; rr!=w5+41; rr+=1) *rr = *ss++;
  /* #28: output[1][0] = @5 */
  casadi_copy(w5, 41, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mhe_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mhe_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mhe_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void mhe_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mhe_cost_y_0_fun_jac_ut_xt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mhe_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mhe_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mhe_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 146;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
