/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mhe_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[33] = {32, 1, 0, 29, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};

/* mhe_expl_vde_adj:(i0[16],i1[16],i2[16],i3[])->(o0[32x1,29nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+8, w2, *w3=w+13, *w4=w+22, *w5=w+38, *w6=w+41, *w7=w+45, *w8=w+48, *w9=w+51, *w10=w+54, *w11=w+57, *w12=w+66, *w13=w+69, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, *w28=w+86, *w29=w+90, *w30=w+94, *w31=w+98, *w32=w+102, *w33=w+106, *w34=w+122;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 16, w4);
  /* #5: {@5, @6, @7, @8, @9} = vertsplit(@4) */
  casadi_copy(w4, 3, w5);
  casadi_copy(w4+3, 4, w6);
  casadi_copy(w4+7, 3, w7);
  casadi_copy(w4+10, 3, w8);
  casadi_copy(w4+13, 3, w9);
  /* #6: @10 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+13 : 0, 3, w10);
  /* #7: @10 = @10' */
  /* #8: @3 = mac(@7,@10,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w10+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #9: @11 = @3' */
  for (i=0, rr=w11, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #10: {@10, @12, @13} = horzsplit(@11) */
  casadi_copy(w11, 3, w10);
  casadi_copy(w11+3, 3, w12);
  casadi_copy(w11+6, 3, w13);
  /* #11: @13 = @13' */
  /* #12: {@14, @15, @16} = horzsplit(@13) */
  w14 = w13[0];
  w15 = w13[1];
  w16 = w13[2];
  /* #13: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #14: @17 = (@2*@15) */
  w17  = (w2*w15);
  /* #15: @18 = @1[2] */
  for (rr=(&w18), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #16: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #17: @19 = (@18*@14) */
  w19  = (w18*w14);
  /* #18: @17 = (@17-@19) */
  w17 -= w19;
  /* #19: @12 = @12' */
  /* #20: {@19, @20, @21} = horzsplit(@12) */
  w19 = w12[0];
  w20 = w12[1];
  w21 = w12[2];
  /* #21: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #22: @22 = (@2*@21) */
  w22  = (w2*w21);
  /* #23: @17 = (@17-@22) */
  w17 -= w22;
  /* #24: @22 = @1[3] */
  for (rr=(&w22), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #25: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #26: @23 = (@22*@19) */
  w23  = (w22*w19);
  /* #27: @17 = (@17+@23) */
  w17 += w23;
  /* #28: @10 = @10' */
  /* #29: {@23, @24, @25} = horzsplit(@10) */
  w23 = w10[0];
  w24 = w10[1];
  w25 = w10[2];
  /* #30: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #31: @26 = (@18*@25) */
  w26  = (w18*w25);
  /* #32: @17 = (@17+@26) */
  w17 += w26;
  /* #33: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #34: @26 = (@22*@24) */
  w26  = (w22*w24);
  /* #35: @17 = (@17-@26) */
  w17 -= w26;
  /* #36: (@0[0] += @17) */
  for (rr=w0+0, ss=(&w17); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #37: @17 = (2.*@2) */
  w17 = (2.* w2 );
  /* #38: @16 = (-@16) */
  w16 = (- w16 );
  /* #39: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #40: @17 = (@17*@16) */
  w17 *= w16;
  /* #41: @26 = @1[0] */
  for (rr=(&w26), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #42: @27 = (@26*@15) */
  w27  = (w26*w15);
  /* #43: @17 = (@17+@27) */
  w17 += w27;
  /* #44: @27 = (@22*@14) */
  w27  = (w22*w14);
  /* #45: @17 = (@17+@27) */
  w17 += w27;
  /* #46: @27 = (@26*@21) */
  w27  = (w26*w21);
  /* #47: @17 = (@17-@27) */
  w17 -= w27;
  /* #48: @27 = (2.*@2) */
  w27 = (2.* w2 );
  /* #49: @20 = (-@20) */
  w20 = (- w20 );
  /* #50: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #51: @27 = (@27*@20) */
  w27 *= w20;
  /* #52: @17 = (@17+@27) */
  w17 += w27;
  /* #53: @27 = (@18*@19) */
  w27  = (w18*w19);
  /* #54: @17 = (@17+@27) */
  w17 += w27;
  /* #55: @27 = (@22*@25) */
  w27  = (w22*w25);
  /* #56: @17 = (@17+@27) */
  w17 += w27;
  /* #57: @27 = (@18*@24) */
  w27  = (w18*w24);
  /* #58: @17 = (@17+@27) */
  w17 += w27;
  /* #59: (@0[1] += @17) */
  for (rr=w0+1, ss=(&w17); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #60: @17 = (@18*@15) */
  w17  = (w18*w15);
  /* #61: @27 = (@2*@14) */
  w27  = (w2*w14);
  /* #62: @17 = (@17+@27) */
  w17 += w27;
  /* #63: @27 = (@18*@21) */
  w27  = (w18*w21);
  /* #64: @17 = (@17+@27) */
  w17 += w27;
  /* #65: @27 = (2.*@22) */
  w27 = (2.* w22 );
  /* #66: @27 = (@27*@20) */
  w27 *= w20;
  /* #67: @17 = (@17+@27) */
  w17 += w27;
  /* #68: @27 = (@26*@19) */
  w27  = (w26*w19);
  /* #69: @17 = (@17+@27) */
  w17 += w27;
  /* #70: @27 = (@2*@25) */
  w27  = (w2*w25);
  /* #71: @17 = (@17+@27) */
  w17 += w27;
  /* #72: @27 = (@26*@24) */
  w27  = (w26*w24);
  /* #73: @17 = (@17-@27) */
  w17 -= w27;
  /* #74: @27 = (2.*@22) */
  w27 = (2.* w22 );
  /* #75: @23 = (-@23) */
  w23 = (- w23 );
  /* #76: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #77: @27 = (@27*@23) */
  w27 *= w23;
  /* #78: @17 = (@17+@27) */
  w17 += w27;
  /* #79: (@0[3] += @17) */
  for (rr=w0+3, ss=(&w17); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #80: @17 = (2.*@18) */
  w17 = (2.* w18 );
  /* #81: @17 = (@17*@16) */
  w17 *= w16;
  /* #82: @15 = (@22*@15) */
  w15  = (w22*w15);
  /* #83: @17 = (@17+@15) */
  w17 += w15;
  /* #84: @14 = (@26*@14) */
  w14  = (w26*w14);
  /* #85: @17 = (@17-@14) */
  w17 -= w14;
  /* #86: @21 = (@22*@21) */
  w21  = (w22*w21);
  /* #87: @17 = (@17+@21) */
  w17 += w21;
  /* #88: @19 = (@2*@19) */
  w19  = (w2*w19);
  /* #89: @17 = (@17+@19) */
  w17 += w19;
  /* #90: @25 = (@26*@25) */
  w25  = (w26*w25);
  /* #91: @17 = (@17+@25) */
  w17 += w25;
  /* #92: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #93: @17 = (@17+@24) */
  w17 += w24;
  /* #94: @24 = (2.*@18) */
  w24 = (2.* w18 );
  /* #95: @24 = (@24*@23) */
  w24 *= w23;
  /* #96: @17 = (@17+@24) */
  w17 += w24;
  /* #97: (@0[2] += @17) */
  for (rr=w0+2, ss=(&w17); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #98: @28 = zeros(4x1) */
  casadi_clear(w28, 4);
  /* #99: @17 = 0 */
  w17 = 0.;
  /* #100: @10 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w10);
  /* #101: @24 = @10[0] */
  for (rr=(&w24), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #102: @24 = (-@24) */
  w24 = (- w24 );
  /* #103: @23 = @10[1] */
  for (rr=(&w23), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #104: @23 = (-@23) */
  w23 = (- w23 );
  /* #105: @25 = @10[2] */
  for (rr=(&w25), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #106: @25 = (-@25) */
  w25 = (- w25 );
  /* #107: @29 = horzcat(@17, @24, @23, @25) */
  rr=w29;
  *rr++ = w17;
  *rr++ = w24;
  *rr++ = w23;
  *rr++ = w25;
  /* #108: @29 = @29' */
  /* #109: @17 = @10[0] */
  for (rr=(&w17), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #110: @24 = 0 */
  w24 = 0.;
  /* #111: @23 = @10[2] */
  for (rr=(&w23), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #112: @25 = @10[1] */
  for (rr=(&w25), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #113: @25 = (-@25) */
  w25 = (- w25 );
  /* #114: @30 = horzcat(@17, @24, @23, @25) */
  rr=w30;
  *rr++ = w17;
  *rr++ = w24;
  *rr++ = w23;
  *rr++ = w25;
  /* #115: @30 = @30' */
  /* #116: @17 = @10[1] */
  for (rr=(&w17), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #117: @24 = @10[2] */
  for (rr=(&w24), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #118: @24 = (-@24) */
  w24 = (- w24 );
  /* #119: @23 = 0 */
  w23 = 0.;
  /* #120: @25 = @10[0] */
  for (rr=(&w25), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #121: @31 = horzcat(@17, @24, @23, @25) */
  rr=w31;
  *rr++ = w17;
  *rr++ = w24;
  *rr++ = w23;
  *rr++ = w25;
  /* #122: @31 = @31' */
  /* #123: @17 = @10[2] */
  for (rr=(&w17), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #124: @24 = @10[1] */
  for (rr=(&w24), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #125: @23 = @10[0] */
  for (rr=(&w23), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #126: @23 = (-@23) */
  w23 = (- w23 );
  /* #127: @25 = 0 */
  w25 = 0.;
  /* #128: @32 = horzcat(@17, @24, @23, @25) */
  rr=w32;
  *rr++ = w17;
  *rr++ = w24;
  *rr++ = w23;
  *rr++ = w25;
  /* #129: @32 = @32' */
  /* #130: @4 = horzcat(@29, @30, @31, @32) */
  rr=w4;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  /* #131: @17 = 0.5 */
  w17 = 5.0000000000000000e-01;
  /* #132: @29 = (@17*@6) */
  for (i=0, rr=w29, cs=w6; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #133: @28 = mac(@4,@29,@28) */
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w4+j, tt=w29+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #134: @0 = (@0+@28) */
  for (i=0, rr=w0, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #135: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #136: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+4);
  /* #137: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #138: @4 = zeros(4x4) */
  casadi_clear(w4, 16);
  /* #139: @1 = @1' */
  /* #140: @4 = mac(@29,@1,@4) */
  for (i=0, rr=w4; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w29+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #141: @33 = @4' */
  for (i=0, rr=w33, cs=w4; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #142: {@29, @1, @0, @28} = horzsplit(@33) */
  casadi_copy(w33, 4, w29);
  casadi_copy(w33+4, 4, w1);
  casadi_copy(w33+8, 4, w0);
  casadi_copy(w33+12, 4, w28);
  /* #143: @28 = @28' */
  /* #144: {@17, @24, @23, NULL} = horzsplit(@28) */
  w17 = w28[0];
  w24 = w28[1];
  w23 = w28[2];
  /* #145: @23 = (-@23) */
  w23 = (- w23 );
  /* #146: (@10[0] += @23) */
  for (rr=w10+0, ss=(&w23); rr!=w10+1; rr+=1) *rr += *ss++;
  /* #147: (@10[1] += @24) */
  for (rr=w10+1, ss=(&w24); rr!=w10+2; rr+=1) *rr += *ss++;
  /* #148: (@10[2] += @17) */
  for (rr=w10+2, ss=(&w17); rr!=w10+3; rr+=1) *rr += *ss++;
  /* #149: @0 = @0' */
  /* #150: {@17, @24, NULL, @23} = horzsplit(@0) */
  w17 = w0[0];
  w24 = w0[1];
  w23 = w0[3];
  /* #151: (@10[0] += @23) */
  for (rr=w10+0, ss=(&w23); rr!=w10+1; rr+=1) *rr += *ss++;
  /* #152: @24 = (-@24) */
  w24 = (- w24 );
  /* #153: (@10[2] += @24) */
  for (rr=w10+2, ss=(&w24); rr!=w10+3; rr+=1) *rr += *ss++;
  /* #154: (@10[1] += @17) */
  for (rr=w10+1, ss=(&w17); rr!=w10+2; rr+=1) *rr += *ss++;
  /* #155: @1 = @1' */
  /* #156: {@17, NULL, @24, @23} = horzsplit(@1) */
  w17 = w1[0];
  w24 = w1[2];
  w23 = w1[3];
  /* #157: @23 = (-@23) */
  w23 = (- w23 );
  /* #158: (@10[1] += @23) */
  for (rr=w10+1, ss=(&w23); rr!=w10+2; rr+=1) *rr += *ss++;
  /* #159: (@10[2] += @24) */
  for (rr=w10+2, ss=(&w24); rr!=w10+3; rr+=1) *rr += *ss++;
  /* #160: (@10[0] += @17) */
  for (rr=w10+0, ss=(&w17); rr!=w10+1; rr+=1) *rr += *ss++;
  /* #161: @29 = @29' */
  /* #162: {NULL, @17, @24, @23} = horzsplit(@29) */
  w17 = w29[1];
  w24 = w29[2];
  w23 = w29[3];
  /* #163: @23 = (-@23) */
  w23 = (- w23 );
  /* #164: (@10[2] += @23) */
  for (rr=w10+2, ss=(&w23); rr!=w10+3; rr+=1) *rr += *ss++;
  /* #165: @24 = (-@24) */
  w24 = (- w24 );
  /* #166: (@10[1] += @24) */
  for (rr=w10+1, ss=(&w24); rr!=w10+2; rr+=1) *rr += *ss++;
  /* #167: @17 = (-@17) */
  w17 = (- w17 );
  /* #168: (@10[0] += @17) */
  for (rr=w10+0, ss=(&w17); rr!=w10+1; rr+=1) *rr += *ss++;
  /* #169: output[0][2] = @10 */
  if (res[0]) casadi_copy(w10, 3, res[0]+7);
  /* #170: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #171: @17 = 1 */
  w17 = 1.;
  /* #172: @24 = sq(@18) */
  w24 = casadi_sq( w18 );
  /* #173: @23 = sq(@22) */
  w23 = casadi_sq( w22 );
  /* #174: @24 = (@24+@23) */
  w24 += w23;
  /* #175: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #176: @17 = (@17-@24) */
  w17 -= w24;
  /* #177: @24 = (@2*@18) */
  w24  = (w2*w18);
  /* #178: @23 = (@26*@22) */
  w23  = (w26*w22);
  /* #179: @24 = (@24-@23) */
  w24 -= w23;
  /* #180: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #181: @23 = (@2*@22) */
  w23  = (w2*w22);
  /* #182: @25 = (@26*@18) */
  w25  = (w26*w18);
  /* #183: @23 = (@23+@25) */
  w23 += w25;
  /* #184: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #185: @12 = horzcat(@17, @24, @23) */
  rr=w12;
  *rr++ = w17;
  *rr++ = w24;
  *rr++ = w23;
  /* #186: @12 = @12' */
  /* #187: @17 = (@2*@18) */
  w17  = (w2*w18);
  /* #188: @24 = (@26*@22) */
  w24  = (w26*w22);
  /* #189: @17 = (@17+@24) */
  w17 += w24;
  /* #190: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #191: @24 = 1 */
  w24 = 1.;
  /* #192: @23 = sq(@2) */
  w23 = casadi_sq( w2 );
  /* #193: @25 = sq(@22) */
  w25 = casadi_sq( w22 );
  /* #194: @23 = (@23+@25) */
  w23 += w25;
  /* #195: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #196: @24 = (@24-@23) */
  w24 -= w23;
  /* #197: @23 = (@18*@22) */
  w23  = (w18*w22);
  /* #198: @25 = (@26*@2) */
  w25  = (w26*w2);
  /* #199: @23 = (@23-@25) */
  w23 -= w25;
  /* #200: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #201: @13 = horzcat(@17, @24, @23) */
  rr=w13;
  *rr++ = w17;
  *rr++ = w24;
  *rr++ = w23;
  /* #202: @13 = @13' */
  /* #203: @17 = (@2*@22) */
  w17  = (w2*w22);
  /* #204: @24 = (@26*@18) */
  w24  = (w26*w18);
  /* #205: @17 = (@17-@24) */
  w17 -= w24;
  /* #206: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #207: @22 = (@18*@22) */
  w22  = (w18*w22);
  /* #208: @26 = (@26*@2) */
  w26 *= w2;
  /* #209: @22 = (@22+@26) */
  w22 += w26;
  /* #210: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #211: @26 = 1 */
  w26 = 1.;
  /* #212: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #213: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #214: @2 = (@2+@18) */
  w2 += w18;
  /* #215: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #216: @26 = (@26-@2) */
  w26 -= w2;
  /* #217: @34 = horzcat(@17, @22, @26) */
  rr=w34;
  *rr++ = w17;
  *rr++ = w22;
  *rr++ = w26;
  /* #218: @34 = @34' */
  /* #219: @11 = horzcat(@12, @13, @34) */
  rr=w11;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #220: @10 = mac(@11,@7,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w11+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #221: output[0][3] = @10 */
  if (res[0]) casadi_copy(w10, 3, res[0]+10);
  /* #222: output[0][4] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+13);
  /* #223: output[0][5] = @6 */
  if (res[0]) casadi_copy(w6, 4, res[0]+16);
  /* #224: output[0][6] = @7 */
  if (res[0]) casadi_copy(w7, 3, res[0]+20);
  /* #225: output[0][7] = @8 */
  if (res[0]) casadi_copy(w8, 3, res[0]+23);
  /* #226: output[0][8] = @9 */
  if (res[0]) casadi_copy(w9, 3, res[0]+26);
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mhe_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mhe_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mhe_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mhe_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mhe_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mhe_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mhe_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mhe_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 125;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
