/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mhe_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., 9.8100000000000005e+00};

/* mhe_expl_ode_fun:(i0[16],i1[16],i2[])->(o0[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+7, w2, *w3=w+11, w4, w5, w6, w7, *w8=w+19, *w9=w+23, *w10=w+27, *w11=w+31, *w12=w+35, *w13=w+51, w14, w15, w16, *w17=w+70, *w18=w+73, *w19=w+76, *w20=w+85;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 3, w1);
  /* #2: @0 = (@0+@1) */
  for (i=0, rr=w0, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #3: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #4: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #5: @3 = zeros(4x1) */
  casadi_clear(w3, 4);
  /* #6: @4 = 0 */
  w4 = 0.;
  /* #7: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #8: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #9: @5 = (-@5) */
  w5 = (- w5 );
  /* #10: @6 = @0[1] */
  for (rr=(&w6), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #11: @6 = (-@6) */
  w6 = (- w6 );
  /* #12: @7 = @0[2] */
  for (rr=(&w7), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #13: @7 = (-@7) */
  w7 = (- w7 );
  /* #14: @8 = horzcat(@4, @5, @6, @7) */
  rr=w8;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #15: @8 = @8' */
  /* #16: @4 = @0[0] */
  for (rr=(&w4), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #17: @5 = 0 */
  w5 = 0.;
  /* #18: @6 = @0[2] */
  for (rr=(&w6), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #19: @7 = @0[1] */
  for (rr=(&w7), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #20: @7 = (-@7) */
  w7 = (- w7 );
  /* #21: @9 = horzcat(@4, @5, @6, @7) */
  rr=w9;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #22: @9 = @9' */
  /* #23: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #24: @5 = @0[2] */
  for (rr=(&w5), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #25: @5 = (-@5) */
  w5 = (- w5 );
  /* #26: @6 = 0 */
  w6 = 0.;
  /* #27: @7 = @0[0] */
  for (rr=(&w7), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #28: @10 = horzcat(@4, @5, @6, @7) */
  rr=w10;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #29: @10 = @10' */
  /* #30: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #31: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #32: @6 = @0[0] */
  for (rr=(&w6), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #33: @6 = (-@6) */
  w6 = (- w6 );
  /* #34: @7 = 0 */
  w7 = 0.;
  /* #35: @11 = horzcat(@4, @5, @6, @7) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #36: @11 = @11' */
  /* #37: @12 = horzcat(@8, @9, @10, @11) */
  rr=w12;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #38: @13 = @12' */
  for (i=0, rr=w13, cs=w12; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #39: @8 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w8);
  /* #40: @3 = mac(@13,@8,@3) */
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w13+j, tt=w8+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #41: @3 = (@2*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #42: @9 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 4, w9);
  /* #43: @3 = (@3+@9) */
  for (i=0, rr=w3, cs=w9; i<4; ++i) (*rr++) += (*cs++);
  /* #44: output[0][1] = @3 */
  if (res[0]) casadi_copy(w3, 4, res[0]+3);
  /* #45: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #46: @2 = 1 */
  w2 = 1.;
  /* #47: @4 = @8[2] */
  for (rr=(&w4), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #48: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #49: @6 = @8[3] */
  for (rr=(&w6), ss=w8+3; ss!=w8+4; ss+=1) *rr++ = *ss;
  /* #50: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #51: @5 = (@5+@7) */
  w5 += w7;
  /* #52: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #53: @2 = (@2-@5) */
  w2 -= w5;
  /* #54: @5 = @8[1] */
  for (rr=(&w5), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #55: @7 = (@5*@4) */
  w7  = (w5*w4);
  /* #56: @14 = @8[0] */
  for (rr=(&w14), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #57: @15 = (@14*@6) */
  w15  = (w14*w6);
  /* #58: @7 = (@7-@15) */
  w7 -= w15;
  /* #59: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #60: @15 = (@5*@6) */
  w15  = (w5*w6);
  /* #61: @16 = (@14*@4) */
  w16  = (w14*w4);
  /* #62: @15 = (@15+@16) */
  w15 += w16;
  /* #63: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #64: @1 = horzcat(@2, @7, @15) */
  rr=w1;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w15;
  /* #65: @1 = @1' */
  /* #66: @2 = (@5*@4) */
  w2  = (w5*w4);
  /* #67: @7 = (@14*@6) */
  w7  = (w14*w6);
  /* #68: @2 = (@2+@7) */
  w2 += w7;
  /* #69: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #70: @7 = 1 */
  w7 = 1.;
  /* #71: @15 = sq(@5) */
  w15 = casadi_sq( w5 );
  /* #72: @16 = sq(@6) */
  w16 = casadi_sq( w6 );
  /* #73: @15 = (@15+@16) */
  w15 += w16;
  /* #74: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #75: @7 = (@7-@15) */
  w7 -= w15;
  /* #76: @15 = (@4*@6) */
  w15  = (w4*w6);
  /* #77: @16 = (@14*@5) */
  w16  = (w14*w5);
  /* #78: @15 = (@15-@16) */
  w15 -= w16;
  /* #79: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #80: @17 = horzcat(@2, @7, @15) */
  rr=w17;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w15;
  /* #81: @17 = @17' */
  /* #82: @2 = (@5*@6) */
  w2  = (w5*w6);
  /* #83: @7 = (@14*@4) */
  w7  = (w14*w4);
  /* #84: @2 = (@2-@7) */
  w2 -= w7;
  /* #85: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #86: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #87: @14 = (@14*@5) */
  w14 *= w5;
  /* #88: @6 = (@6+@14) */
  w6 += w14;
  /* #89: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #90: @14 = 1 */
  w14 = 1.;
  /* #91: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #92: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #93: @5 = (@5+@4) */
  w5 += w4;
  /* #94: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #95: @14 = (@14-@5) */
  w14 -= w5;
  /* #96: @18 = horzcat(@2, @6, @14) */
  rr=w18;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w14;
  /* #97: @18 = @18' */
  /* #98: @19 = horzcat(@1, @17, @18) */
  rr=w19;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #99: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #100: @1 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+13 : 0, 3, w1);
  /* #101: @0 = mac(@20,@1,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #102: @1 = [0, 0, 9.81] */
  casadi_copy(casadi_c0, 3, w1);
  /* #103: @0 = (@0-@1) */
  for (i=0, rr=w0, cs=w1; i<3; ++i) (*rr++) -= (*cs++);
  /* #104: @1 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+7 : 0, 3, w1);
  /* #105: @0 = (@0+@1) */
  for (i=0, rr=w0, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #106: output[0][2] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+7);
  /* #107: @0 = input[1][3] */
  casadi_copy(arg[1] ? arg[1]+10 : 0, 3, w0);
  /* #108: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+10);
  /* #109: @0 = input[1][4] */
  casadi_copy(arg[1] ? arg[1]+13 : 0, 3, w0);
  /* #110: output[0][4] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+13);
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mhe_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mhe_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mhe_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mhe_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mhe_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int mhe_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mhe_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mhe_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 94;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
