/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[4] = {5.0000000000000003e-02, -5.0000000000000003e-02, 5.0000000000000003e-02, -5.0000000000000003e-02};
static const casadi_real casadi_c1[4] = {1.7000000000000001e-01, 0., -1.7000000000000001e-01, 0.};
static const casadi_real casadi_c2[4] = {0., 1.7000000000000001e-01, 0., -1.7000000000000001e-01};

/* mpc_expl_vde_adj:(i0[13],i1[13],i2[4],i3)->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+8, w2, *w3=w+13, *w4=w+22, *w5=w+35, *w6=w+38, *w7=w+42, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+55, *w19=w+59, *w20=w+62, *w21=w+71, *w22=w+74, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+86, *w33=w+90, *w34=w+94, *w35=w+98, *w36=w+102, *w37=w+118;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 13, w4);
  /* #5: {@5, @6, @7, @8, @9, @10} = vertsplit(@4) */
  casadi_copy(w4, 3, w5);
  casadi_copy(w4+3, 4, w6);
  casadi_copy(w4+7, 3, w7);
  w8 = w4[10];
  w9 = w4[11];
  w10 = w4[12];
  /* #6: @11 = 0 */
  w11 = 0.;
  /* #7: @12 = 0 */
  w12 = 0.;
  /* #8: @13 = 34.1943 */
  w13 = 3.4194319999999998e+01;
  /* #9: @14 = input[2][0] */
  w14 = arg[2] ? arg[2][0] : 0;
  /* #10: @15 = input[2][1] */
  w15 = arg[2] ? arg[2][1] : 0;
  /* #11: @16 = input[2][2] */
  w16 = arg[2] ? arg[2][2] : 0;
  /* #12: @17 = input[2][3] */
  w17 = arg[2] ? arg[2][3] : 0;
  /* #13: @18 = vertcat(@14, @15, @16, @17) */
  rr=w18;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #14: @18 = (@13*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #15: @14 = @18[0] */
  for (rr=(&w14), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #16: @15 = @18[1] */
  for (rr=(&w15), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #17: @14 = (@14+@15) */
  w14 += w15;
  /* #18: @15 = @18[2] */
  for (rr=(&w15), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #19: @14 = (@14+@15) */
  w14 += w15;
  /* #20: @15 = @18[3] */
  for (rr=(&w15), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #21: @14 = (@14+@15) */
  w14 += w15;
  /* #22: @19 = vertcat(@11, @12, @14) */
  rr=w19;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w14;
  /* #23: @11 = 0.716 */
  w11 = 7.1600000000000008e-01;
  /* #24: @12 = input[3][0] */
  w12 = arg[3] ? arg[3][0] : 0;
  /* #25: @11 = (@11+@12) */
  w11 += w12;
  /* #26: @19 = (@19/@11) */
  for (i=0, rr=w19; i<3; ++i) (*rr++) /= w11;
  /* #27: @19 = @19' */
  /* #28: @3 = mac(@7,@19,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w19+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #29: @20 = @3' */
  for (i=0, rr=w20, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #30: {@19, @21, @22} = horzsplit(@20) */
  casadi_copy(w20, 3, w19);
  casadi_copy(w20+3, 3, w21);
  casadi_copy(w20+6, 3, w22);
  /* #31: @22 = @22' */
  /* #32: {@12, @14, @15} = horzsplit(@22) */
  w12 = w22[0];
  w14 = w22[1];
  w15 = w22[2];
  /* #33: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #34: @16 = (@2*@14) */
  w16  = (w2*w14);
  /* #35: @17 = @1[2] */
  for (rr=(&w17), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #36: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #37: @23 = (@17*@12) */
  w23  = (w17*w12);
  /* #38: @16 = (@16-@23) */
  w16 -= w23;
  /* #39: @21 = @21' */
  /* #40: {@23, @24, @25} = horzsplit(@21) */
  w23 = w21[0];
  w24 = w21[1];
  w25 = w21[2];
  /* #41: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #42: @26 = (@2*@25) */
  w26  = (w2*w25);
  /* #43: @16 = (@16-@26) */
  w16 -= w26;
  /* #44: @26 = @1[3] */
  for (rr=(&w26), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #45: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #46: @27 = (@26*@23) */
  w27  = (w26*w23);
  /* #47: @16 = (@16+@27) */
  w16 += w27;
  /* #48: @19 = @19' */
  /* #49: {@27, @28, @29} = horzsplit(@19) */
  w27 = w19[0];
  w28 = w19[1];
  w29 = w19[2];
  /* #50: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #51: @30 = (@17*@29) */
  w30  = (w17*w29);
  /* #52: @16 = (@16+@30) */
  w16 += w30;
  /* #53: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #54: @30 = (@26*@28) */
  w30  = (w26*w28);
  /* #55: @16 = (@16-@30) */
  w16 -= w30;
  /* #56: (@0[0] += @16) */
  for (rr=w0+0, ss=(&w16); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #57: @16 = (2.*@2) */
  w16 = (2.* w2 );
  /* #58: @15 = (-@15) */
  w15 = (- w15 );
  /* #59: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #60: @16 = (@16*@15) */
  w16 *= w15;
  /* #61: @30 = @1[0] */
  for (rr=(&w30), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #62: @31 = (@30*@14) */
  w31  = (w30*w14);
  /* #63: @16 = (@16+@31) */
  w16 += w31;
  /* #64: @31 = (@26*@12) */
  w31  = (w26*w12);
  /* #65: @16 = (@16+@31) */
  w16 += w31;
  /* #66: @31 = (@30*@25) */
  w31  = (w30*w25);
  /* #67: @16 = (@16-@31) */
  w16 -= w31;
  /* #68: @31 = (2.*@2) */
  w31 = (2.* w2 );
  /* #69: @24 = (-@24) */
  w24 = (- w24 );
  /* #70: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #71: @31 = (@31*@24) */
  w31 *= w24;
  /* #72: @16 = (@16+@31) */
  w16 += w31;
  /* #73: @31 = (@17*@23) */
  w31  = (w17*w23);
  /* #74: @16 = (@16+@31) */
  w16 += w31;
  /* #75: @31 = (@26*@29) */
  w31  = (w26*w29);
  /* #76: @16 = (@16+@31) */
  w16 += w31;
  /* #77: @31 = (@17*@28) */
  w31  = (w17*w28);
  /* #78: @16 = (@16+@31) */
  w16 += w31;
  /* #79: (@0[1] += @16) */
  for (rr=w0+1, ss=(&w16); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #80: @16 = (@17*@14) */
  w16  = (w17*w14);
  /* #81: @31 = (@2*@12) */
  w31  = (w2*w12);
  /* #82: @16 = (@16+@31) */
  w16 += w31;
  /* #83: @31 = (@17*@25) */
  w31  = (w17*w25);
  /* #84: @16 = (@16+@31) */
  w16 += w31;
  /* #85: @31 = (2.*@26) */
  w31 = (2.* w26 );
  /* #86: @31 = (@31*@24) */
  w31 *= w24;
  /* #87: @16 = (@16+@31) */
  w16 += w31;
  /* #88: @31 = (@30*@23) */
  w31  = (w30*w23);
  /* #89: @16 = (@16+@31) */
  w16 += w31;
  /* #90: @31 = (@2*@29) */
  w31  = (w2*w29);
  /* #91: @16 = (@16+@31) */
  w16 += w31;
  /* #92: @31 = (@30*@28) */
  w31  = (w30*w28);
  /* #93: @16 = (@16-@31) */
  w16 -= w31;
  /* #94: @31 = (2.*@26) */
  w31 = (2.* w26 );
  /* #95: @27 = (-@27) */
  w27 = (- w27 );
  /* #96: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #97: @31 = (@31*@27) */
  w31 *= w27;
  /* #98: @16 = (@16+@31) */
  w16 += w31;
  /* #99: (@0[3] += @16) */
  for (rr=w0+3, ss=(&w16); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #100: @16 = (2.*@17) */
  w16 = (2.* w17 );
  /* #101: @16 = (@16*@15) */
  w16 *= w15;
  /* #102: @14 = (@26*@14) */
  w14  = (w26*w14);
  /* #103: @16 = (@16+@14) */
  w16 += w14;
  /* #104: @12 = (@30*@12) */
  w12  = (w30*w12);
  /* #105: @16 = (@16-@12) */
  w16 -= w12;
  /* #106: @25 = (@26*@25) */
  w25  = (w26*w25);
  /* #107: @16 = (@16+@25) */
  w16 += w25;
  /* #108: @23 = (@2*@23) */
  w23  = (w2*w23);
  /* #109: @16 = (@16+@23) */
  w16 += w23;
  /* #110: @29 = (@30*@29) */
  w29  = (w30*w29);
  /* #111: @16 = (@16+@29) */
  w16 += w29;
  /* #112: @28 = (@2*@28) */
  w28  = (w2*w28);
  /* #113: @16 = (@16+@28) */
  w16 += w28;
  /* #114: @28 = (2.*@17) */
  w28 = (2.* w17 );
  /* #115: @28 = (@28*@27) */
  w28 *= w27;
  /* #116: @16 = (@16+@28) */
  w16 += w28;
  /* #117: (@0[2] += @16) */
  for (rr=w0+2, ss=(&w16); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #118: @18 = zeros(4x1) */
  casadi_clear(w18, 4);
  /* #119: @16 = 0 */
  w16 = 0.;
  /* #120: @19 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w19);
  /* #121: @28 = @19[0] */
  for (rr=(&w28), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #122: @28 = (-@28) */
  w28 = (- w28 );
  /* #123: @27 = @19[1] */
  for (rr=(&w27), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #124: @27 = (-@27) */
  w27 = (- w27 );
  /* #125: @29 = @19[2] */
  for (rr=(&w29), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #126: @29 = (-@29) */
  w29 = (- w29 );
  /* #127: @32 = horzcat(@16, @28, @27, @29) */
  rr=w32;
  *rr++ = w16;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w29;
  /* #128: @32 = @32' */
  /* #129: @16 = @19[0] */
  for (rr=(&w16), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #130: @28 = 0 */
  w28 = 0.;
  /* #131: @27 = @19[2] */
  for (rr=(&w27), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #132: @29 = @19[1] */
  for (rr=(&w29), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #133: @29 = (-@29) */
  w29 = (- w29 );
  /* #134: @33 = horzcat(@16, @28, @27, @29) */
  rr=w33;
  *rr++ = w16;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w29;
  /* #135: @33 = @33' */
  /* #136: @16 = @19[1] */
  for (rr=(&w16), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #137: @28 = @19[2] */
  for (rr=(&w28), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #138: @28 = (-@28) */
  w28 = (- w28 );
  /* #139: @27 = 0 */
  w27 = 0.;
  /* #140: @29 = @19[0] */
  for (rr=(&w29), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #141: @34 = horzcat(@16, @28, @27, @29) */
  rr=w34;
  *rr++ = w16;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w29;
  /* #142: @34 = @34' */
  /* #143: @16 = @19[2] */
  for (rr=(&w16), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #144: @28 = @19[1] */
  for (rr=(&w28), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #145: @27 = @19[0] */
  for (rr=(&w27), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #146: @27 = (-@27) */
  w27 = (- w27 );
  /* #147: @29 = 0 */
  w29 = 0.;
  /* #148: @35 = horzcat(@16, @28, @27, @29) */
  rr=w35;
  *rr++ = w16;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w29;
  /* #149: @35 = @35' */
  /* #150: @36 = horzcat(@32, @33, @34, @35) */
  rr=w36;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  /* #151: @16 = 0.5 */
  w16 = 5.0000000000000000e-01;
  /* #152: @6 = (@16*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w16*(*cs++));
  /* #153: @18 = mac(@36,@6,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w36+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #154: @0 = (@0+@18) */
  for (i=0, rr=w0, cs=w18; i<4; ++i) (*rr++) += (*cs++);
  /* #155: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #156: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+4);
  /* #157: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #158: @16 = 0.005 */
  w16 = 5.0000000000000001e-03;
  /* #159: @28 = @19[2] */
  for (rr=(&w28), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #160: @28 = (@16*@28) */
  w28  = (w16*w28);
  /* #161: @27 = 142.857 */
  w27 = 1.4285714285714286e+02;
  /* #162: @27 = (@27*@9) */
  w27 *= w9;
  /* #163: @28 = (@28*@27) */
  w28 *= w27;
  /* #164: (@5[0] += @28) */
  for (rr=w5+0, ss=(&w28); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #165: @28 = @19[0] */
  for (rr=(&w28), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #166: @28 = (@28*@27) */
  w28 *= w27;
  /* #167: @16 = (@16*@28) */
  w16 *= w28;
  /* #168: (@5[2] += @16) */
  for (rr=w5+2, ss=(&w16); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #169: @16 = -0.005 */
  w16 = -5.0000000000000001e-03;
  /* #170: @28 = @19[1] */
  for (rr=(&w28), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #171: @28 = (@16*@28) */
  w28  = (w16*w28);
  /* #172: @9 = 142.857 */
  w9 = 1.4285714285714286e+02;
  /* #173: @9 = (@9*@8) */
  w9 *= w8;
  /* #174: @28 = (@28*@9) */
  w28 *= w9;
  /* #175: (@5[2] += @28) */
  for (rr=w5+2, ss=(&w28); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #176: @28 = @19[2] */
  for (rr=(&w28), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #177: @28 = (@28*@9) */
  w28 *= w9;
  /* #178: @16 = (@16*@28) */
  w16 *= w28;
  /* #179: (@5[1] += @16) */
  for (rr=w5+1, ss=(&w16); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #180: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #181: @1 = @1' */
  /* #182: @36 = mac(@6,@1,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w6+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #183: @37 = @36' */
  for (i=0, rr=w37, cs=w36; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #184: {@6, @1, @0, @18} = horzsplit(@37) */
  casadi_copy(w37, 4, w6);
  casadi_copy(w37+4, 4, w1);
  casadi_copy(w37+8, 4, w0);
  casadi_copy(w37+12, 4, w18);
  /* #185: @18 = @18' */
  /* #186: {@16, @28, @8, NULL} = horzsplit(@18) */
  w16 = w18[0];
  w28 = w18[1];
  w8 = w18[2];
  /* #187: @8 = (-@8) */
  w8 = (- w8 );
  /* #188: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #189: (@5[1] += @28) */
  for (rr=w5+1, ss=(&w28); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #190: (@5[2] += @16) */
  for (rr=w5+2, ss=(&w16); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #191: @0 = @0' */
  /* #192: {@16, @28, NULL, @8} = horzsplit(@0) */
  w16 = w0[0];
  w28 = w0[1];
  w8 = w0[3];
  /* #193: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #194: @28 = (-@28) */
  w28 = (- w28 );
  /* #195: (@5[2] += @28) */
  for (rr=w5+2, ss=(&w28); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #196: (@5[1] += @16) */
  for (rr=w5+1, ss=(&w16); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #197: @1 = @1' */
  /* #198: {@16, NULL, @28, @8} = horzsplit(@1) */
  w16 = w1[0];
  w28 = w1[2];
  w8 = w1[3];
  /* #199: @8 = (-@8) */
  w8 = (- w8 );
  /* #200: (@5[1] += @8) */
  for (rr=w5+1, ss=(&w8); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #201: (@5[2] += @28) */
  for (rr=w5+2, ss=(&w28); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #202: (@5[0] += @16) */
  for (rr=w5+0, ss=(&w16); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #203: @6 = @6' */
  /* #204: {NULL, @16, @28, @8} = horzsplit(@6) */
  w16 = w6[1];
  w28 = w6[2];
  w8 = w6[3];
  /* #205: @8 = (-@8) */
  w8 = (- w8 );
  /* #206: (@5[2] += @8) */
  for (rr=w5+2, ss=(&w8); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #207: @28 = (-@28) */
  w28 = (- w28 );
  /* #208: (@5[1] += @28) */
  for (rr=w5+1, ss=(&w28); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #209: @16 = (-@16) */
  w16 = (- w16 );
  /* #210: (@5[0] += @16) */
  for (rr=w5+0, ss=(&w16); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #211: output[0][2] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+7);
  /* #212: @16 = 34.1943 */
  w16 = 3.4194319999999998e+01;
  /* #213: @28 = 83.3333 */
  w28 = 8.3333333333333329e+01;
  /* #214: @28 = (@28*@10) */
  w28 *= w10;
  /* #215: @6 = [0.05, -0.05, 0.05, -0.05] */
  casadi_copy(casadi_c0, 4, w6);
  /* #216: @6 = @6' */
  /* #217: @6 = (@28*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w28*(*cs++));
  /* #218: @6 = @6' */
  /* #219: @1 = [0.17, 0, -0.17, 0] */
  casadi_copy(casadi_c1, 4, w1);
  /* #220: @1 = @1' */
  /* #221: @1 = (@27*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w27*(*cs++));
  /* #222: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #223: @1 = @1' */
  /* #224: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #225: @1 = [0, 0.17, 0, -0.17] */
  casadi_copy(casadi_c2, 4, w1);
  /* #226: @1 = @1' */
  /* #227: @1 = (@9*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #228: @1 = @1' */
  /* #229: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #230: @6 = (@16*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w16*(*cs++));
  /* #231: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #232: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #233: @16 = 1 */
  w16 = 1.;
  /* #234: @9 = sq(@17) */
  w9 = casadi_sq( w17 );
  /* #235: @27 = sq(@26) */
  w27 = casadi_sq( w26 );
  /* #236: @9 = (@9+@27) */
  w9 += w27;
  /* #237: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #238: @16 = (@16-@9) */
  w16 -= w9;
  /* #239: @9 = (@2*@17) */
  w9  = (w2*w17);
  /* #240: @27 = (@30*@26) */
  w27  = (w30*w26);
  /* #241: @9 = (@9-@27) */
  w9 -= w27;
  /* #242: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #243: @27 = (@2*@26) */
  w27  = (w2*w26);
  /* #244: @28 = (@30*@17) */
  w28  = (w30*w17);
  /* #245: @27 = (@27+@28) */
  w27 += w28;
  /* #246: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #247: @19 = horzcat(@16, @9, @27) */
  rr=w19;
  *rr++ = w16;
  *rr++ = w9;
  *rr++ = w27;
  /* #248: @19 = @19' */
  /* #249: @16 = (@2*@17) */
  w16  = (w2*w17);
  /* #250: @9 = (@30*@26) */
  w9  = (w30*w26);
  /* #251: @16 = (@16+@9) */
  w16 += w9;
  /* #252: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #253: @9 = 1 */
  w9 = 1.;
  /* #254: @27 = sq(@2) */
  w27 = casadi_sq( w2 );
  /* #255: @28 = sq(@26) */
  w28 = casadi_sq( w26 );
  /* #256: @27 = (@27+@28) */
  w27 += w28;
  /* #257: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #258: @9 = (@9-@27) */
  w9 -= w27;
  /* #259: @27 = (@17*@26) */
  w27  = (w17*w26);
  /* #260: @28 = (@30*@2) */
  w28  = (w30*w2);
  /* #261: @27 = (@27-@28) */
  w27 -= w28;
  /* #262: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #263: @21 = horzcat(@16, @9, @27) */
  rr=w21;
  *rr++ = w16;
  *rr++ = w9;
  *rr++ = w27;
  /* #264: @21 = @21' */
  /* #265: @16 = (@2*@26) */
  w16  = (w2*w26);
  /* #266: @9 = (@30*@17) */
  w9  = (w30*w17);
  /* #267: @16 = (@16-@9) */
  w16 -= w9;
  /* #268: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #269: @26 = (@17*@26) */
  w26  = (w17*w26);
  /* #270: @30 = (@30*@2) */
  w30 *= w2;
  /* #271: @26 = (@26+@30) */
  w26 += w30;
  /* #272: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #273: @30 = 1 */
  w30 = 1.;
  /* #274: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #275: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #276: @2 = (@2+@17) */
  w2 += w17;
  /* #277: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #278: @30 = (@30-@2) */
  w30 -= w2;
  /* #279: @22 = horzcat(@16, @26, @30) */
  rr=w22;
  *rr++ = w16;
  *rr++ = w26;
  *rr++ = w30;
  /* #280: @22 = @22' */
  /* #281: @20 = horzcat(@19, @21, @22) */
  rr=w20;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #282: @5 = mac(@20,@7,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #283: @5 = (@5/@11) */
  for (i=0, rr=w5; i<3; ++i) (*rr++) /= w11;
  /* #284: {NULL, NULL, @11} = vertsplit(@5) */
  w11 = w5[2];
  /* #285: (@1[3] += @11) */
  for (rr=w1+3, ss=(&w11); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #286: (@1[2] += @11) */
  for (rr=w1+2, ss=(&w11); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #287: (@1[1] += @11) */
  for (rr=w1+1, ss=(&w11); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #288: (@1[0] += @11) */
  for (rr=w1+0, ss=(&w11); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #289: @1 = (@13*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #290: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #291: {@13, @11, @16, @26} = vertsplit(@6) */
  w13 = w6[0];
  w11 = w6[1];
  w16 = w6[2];
  w26 = w6[3];
  /* #292: output[0][3] = @13 */
  if (res[0]) res[0][10] = w13;
  /* #293: output[0][4] = @11 */
  if (res[0]) res[0][11] = w11;
  /* #294: output[0][5] = @16 */
  if (res[0]) res[0][12] = w16;
  /* #295: output[0][6] = @26 */
  if (res[0]) res[0][13] = w26;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 134;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
